FROM registry.access.redhat.com/ubi9/python-312-minimal:latest AS production

ARG AAP_GATEWAY_URL
ARG AAP_SERVICE_URL
ARG HOST
ARG PORT

ENV AAP_GATEWAY_URL=${AAP_GATEWAY_URL}
ENV AAP_SERVICE_URL=${AAP_SERVICE_URL}
ENV OPENAPI_SPEC_URL="file:///var/www/aap-lightspeed-api.yaml"
ENV HOST=${HOST}
ENV PORT=${PORT}
ENV PYTHONUNBUFFERED=1
ENV DEBUG=True

USER root
WORKDIR /var/www/

COPY ansible_mcp_tools/ ./ansible_mcp_tools/
COPY aap_lightspeed_api_1_0/server.py ./
COPY aap_lightspeed_api_1_0/aap-lightspeed-api.yaml ./
COPY aap_lightspeed_api_1_0/pyproject.toml ./pyproject.toml

RUN python -m pip install --no-cache-dir --no-binary=all .

USER 1000

# Launch!
ENTRYPOINT ["python3.12", "server.py"]

EXPOSE ${PORT}
